name: Stephen Scott

include:        ["_pages"]

markdown: kramdown

#permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap

collections:
microblog:
  output: true
  permalink: /microblog/:year/:month/:slug/
